### ISSUE TITLE
license

### ISSUE THREAD

**Issue by MangoIV** [NorfairKing/weeder-nix#1]
Hi! It would be nice to be able to use this but it appears this is only source available. Is this intentional?

**Comment by MangoIV** [comment]
Thank you so much in advance, really cool stuff <3

**Comment by NorfairKing** [comment]
@MangoIV I haven't chosen a license yet.
Before I do: Do you have any requirements of a license? I.e. would gpl be good enough for you?

**Comment by MangoIV** [comment]
Hi! [wire-server](https://github.com/wireapp/wire-server/) is agpl v3 so anything that is compatible with that would be good for me. 

I will suggest to sponsor you but I can't promise anything ;) 

It's not that urgent, so please don't feel pressed to publish under a specific license, just looking into different options :)

**Comment by NorfairKing** [comment]
@MangoIV I think it'll be GPL (for sharing improvements) or BSD license (because that's what weeder uses).
Please let me know if those two work (I checked but I'm not sure).

**Comment by MangoIV** [comment]
I think BSD like weeder does would be best UI wise, like this people who use weeder can just use `weeder-nix` without worrying, no? :P 

As in, if they can't use weeder, then they probably also can't use weeder-nix and vice versa :3

**Comment by sellout** [comment]
My vote is always for GPL licenses, but BSD or similar certainly wouldn’t get in my way.

**Comment by NorfairKing** [comment]
I'll follow `weeder`'s license to contribute in the same spirit.
